# Generated by Django 5.1.4 on 2025-01-03 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='expiration_date',
            field=models.DateField(),
        ),
    ]
